# permissions for end users to edit virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-cloud-resource-manager
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-editor-role
rules:
- apiGroups:
  - greenops.greenops.test
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenops.greenops.test
  resources:
  - virtualmachines/status
  verbs:
  - get
